### ISSUE TITLE
This addon needs an updated inputstream.adaptive

### ISSUE THREAD

**Issue by michaelarnauts** [michaelarnauts/plugin.video.vtm.go#101]
In an attempt to clean up the issues a bit, I will create this meta-issue that is tracking the release of `inputstream.adaptive` for Kodi 18.

Without this update, this will have many issues related to playback of Live TV and VOD (https://github.com/michaelarnauts/plugin.video.vtm.go/issues/1, https://github.com/michaelarnauts/plugin.video.vtm.go/issues/8, https://github.com/michaelarnauts/plugin.video.vtm.go/issues/28).

The [README.md](https://github.com/michaelarnauts/plugin.video.vtm.go#inputstream-adaptive) contains more information on how to get an updated `inputstream.adaptive`.

**Comment by peno64** [comment]
To build inputstream adaptive for raspberry pi yourself, the following instructions are more complete and don't require to build in your home folder but in any location. This is done on a raspbian os on the pi.

sudo apt install autoconf bison build-essential curl default-jdk gawk git gperf libcurl4-openssl-dev zlib1g-dev cmake zip

cd <folder> # folder where you want to build everything

git clone https://github.com/raspberrypi/tools --depth=1
git clone https://github.com/raspberrypi/firmware --depth=1

git clone -b Leia https://github.com/xbmc/xbmc.git
git clone https://github.com/peak3d/inputstream.adaptive
cd inputstream.adaptive && mkdir build && cd build
cmake -DADDONS_TO_BUILD=inputstream.adaptive -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons
make
cd ../../xbmc/addons/
zip -r /tmp/inputstream.adaptive.zip inputstream.adaptive

This will create inputstream.adaptive.zip in the /tmp folder

**Comment by michaelarnauts** [comment]
Thanks @peno64. I've updated the README for this.

**Comment by edd--** [comment]
After reinstalling OSMC's October update the plugin crashes Kodi when starting a live stream. I guess this is input stream.adaptive related. I tried recompiling it but still the same issue ... Any ideas ?

**Comment by michaelarnauts** [comment]
In case you have a Vero4K+, my instructions were incomplete. 
I'm using the latest update, and I don't seem to have any issues. Make sure you clean up the `/usr/lib/kodi/addons/inputstream.adaptive` and ` /usr/share/kodi/addons/inputstream.adaptive` folders. The binaries should be placed in `lib`, the other files in `share`.

Like this:
```
root@osmc:/usr/share/kodi/addons/inputstream.adaptive# ls -lah
total 28K
drwxr-xr-x   3 root root 4,0K okt 31 20:44 .
drwxr-xr-x 198 root root  12K okt 30 12:59 ..
-rw-r--r--   1 root root 2,0K okt 31 20:41 addon.xml
-rw-r--r--   1 root root  424 okt 31 20:41 changelog.txt
drwxr-xr-x   3 root root 4,0K okt 31 16:51 resources
```

```
root@osmc:/usr/lib/kodi/addons/inputstream.adaptive# ls -lah
total 2,7M
drwxr-xr-x  2 root root 4,0K okt 31 20:44 .
drwxr-xr-x 63 root root 4,0K okt  8 19:41 ..
lrwxrwxrwx  1 root root   28 okt 30 22:56 inputstream.adaptive.so -> inputstream.adaptive.so.18.4
lrwxrwxrwx  1 root root   29 okt 31 16:52 inputstream.adaptive.so.18.4 -> inputstream.adaptive.so.2.4.0
-rw-r--r--  1 root root 1,9M okt 30 18:43 inputstream.adaptive.so.2.4.0
-rw-r--r--  1 root root 843K okt 30 22:54 libssd_wv.so
```

**Comment by michaelarnauts** [comment]
Thinking about it, this is probably valid for all OSMC installs, not just the ones on the Vero4K+. OSMC packages `inputstream.adaptive` in the `vero3-mediacenter-osmc` package.

See this output:
```
# dpkg -L vero3-mediacenter-osmc | grep "inputstream.adaptive" | sort
/usr/lib/kodi/addons/inputstream.adaptive
/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so
/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.18.4
/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.2
/usr/lib/kodi/addons/inputstream.adaptive/libssd_wv.so
/usr/share/kodi/addons/inputstream.adaptive
/usr/share/kodi/addons/inputstream.adaptive/addon.xml
/usr/share/kodi/addons/inputstream.adaptive/changelog.txt
/usr/share/kodi/addons/inputstream.adaptive/resources
/usr/share/kodi/addons/inputstream.adaptive/resources/language
/usr/share/kodi/addons/inputstream.adaptive/resources/language/resource.language.en_gb
/usr/share/kodi/addons/inputstream.adaptive/resources/language/resource.language.en_gb/strings.po
/usr/share/kodi/addons/inputstream.adaptive/resources/settings.xml
```

**Comment by edd--** [comment]
ok, works again, thanks !!

**Comment by dagwieers** [comment]
We could use a new set of builds of inputstream.adaptive for Kodi v18.
If possible, please version it as 2.4.2.X

**Comment by peno64** [comment]
@dagwieers 
At who are you asking this question about a new build of inputstream.adaptive for kodi 18? Do you mean that the ones referenced in https://github.com/michaelarnauts/plugin.video.vtm.go/wiki/Inputstream-Adaptive aren't ok anymore and that they should be rebuild? I am still using that one on my pi and it works but still with the problem that I have to pause in the beginning between the commercial and the actual play and then continue for it to work. But last weekend I did compile a new version of inputstream.adaptive and checked but this is still the same.
Why isn't the kodi team building and providing this new version should be more the question I think.

**Comment by michaelarnauts** [comment]
I've rebuild a version based on https://github.com/peak3d/inputstream.adaptive/commit/cc6e32d84994e6d61b9a72d90fc5ccc5f872e0fa for osmc. I've changed the version so it's 2.5.3.1 (latest release is 2.5.3 (for Matrix), but this includes an additional fix we need).

[inputstream.adaptive-2.5.3.1.zip](https://github.com/michaelarnauts/plugin.video.vtm.go/files/3896049/inputstream.adaptive-2.5.3.1.zip)

**Comment by michaelarnauts** [comment]
> Why isn't the kodi team building and providing this new version should be more the question I think.

`inputstream.adaptive` releases are handled by @peak3d, but current development is only happening in the master branch for Kodi 19. It is however possible to run that code on Kodi 18, so I'm not totally sure why he doesn't merge the master branch back to the Leia branch.

I would love a release for Leia with the current code from master.

**Comment by peak3d** [comment]
> I'm not totally sure why he doesn't merge the master branch back to the Leia branch.

Because it takes time, and time is currently something I have not much left.

Which things should be backported to Leia branch?

**Comment by peno64** [comment]
Especially because the latest Leia version 18.5 is said to be the last version of version 18 so I guess version 18 will now remain quite stable for several months

**Comment by peak3d** [comment]
We produce still Leia nightlies, and I would bet that there will be a 18.6 coming.

**Comment by michaelarnauts** [comment]
> > I'm not totally sure why he doesn't merge the master branch back to the Leia branch.
> 
> Because it takes time, and time is currently something I have not much left.
> 
> Which things should be backported to Leia branch?

I understand completely. What I need for this project is the Period implementations (and your related fixes). I just tried to merge master into Leia, and there are no conflicts besides the travis and appveyor files. It's hard for users to compile their own inputstream.adaptive, but if a new release for Leia is made, all other build scripts should pick this up, and after a while, all installations should be upgraded to the updated version.

I haven't fully tested inputstream adaptive for other services (YouTube, Netflix, ...) so that might need some more testing.

**Comment by michaelarnauts** [comment]
> We produce still Leia nightlies, and I would bet that there will be a 18.6 coming.

That's possible, but the Leia branch (and so the nighlies also) doesn't contain all the required Period fixes if I remember correctly.

**Comment by peak3d** [comment]
Yes, but there a a few other things we wanted to backport, the changes in kodi are not that much, let me see

**Comment by michaelarnauts** [comment]
Cool, thanks! I basicly want a user to be able to install this addon on the latest stable Kodi (18), without having to update his inputstream adaptive manually.

**Comment by dagwieers** [comment]
@peak3d It is the only thing preventing us from pushing the VTM GO add-on to the Kodi repository. Thanks for all your help. Let us know if we can help in any way.

**Comment by dagwieers** [comment]
BTW I have been testing @peno64's Leia build for RPi since he offered it (6 weeks), using Youtube and Netflix frequently, so I am confident this works fine.

**Comment by michaelarnauts** [comment]
I think my build isn't completely okay. I've tried building the Leia branch of IA for osmc, and there I also have issues with the Netflix addon, while vtm go is okay, so it's something with my build.

**Comment by dagwieers** [comment]
@peak3d While you're at it, we have a subtitle-fix we would like to see backported to the Leia branch as well. See: https://github.com/pietje666/plugin.video.vrt.nu/issues/45

PS Beware that this issue tracked two issues, the first one was fixed in the Leia branch IIRC, but the second issue was only released in the Matrix branch.

**Comment by michaelarnauts** [comment]
For users on OSMC on a Vero4K+, unzip [this file](https://github.com/michaelarnauts/plugin.video.vtm.go/files/4110563/inputstream.adaptive.so.2.4.zip) and overwrite it in `/usr/lib/kodi/addons/inputstream.adaptive/`.

This build supports periods, and doesn't break netflix.

**Comment by KBET80** [comment]
Anybody has a link to a build for windows? Seems like the links in the https://github.com/michaelarnauts/plugin.video.vtm.go/wiki/Inputstream-Adaptive are down.

**Comment by peno64** [comment]
@michaelarnauts
Note that the link https://github.com/michaelarnauts/plugin.video.vtm.go/wiki/Inputstream-Adaptive for raspberry pi says Raspbery pi (Openelec). I don't know if it works on openelec. I work and tested it on libreelec soy maybe it is better to libreelec instead of openelec. There is a good chance that it also works on openelec but I don't really know

**Comment by peno64** [comment]
See https://github.com/peak3d/inputstream.adaptive/issues/330

**Comment by peno64** [comment]
@KBET80 
The latest windows build of inputstream.adaptive can be found here: https://jenkins.kodi.tv/blue/organizations/jenkins/peak3d%2Finputstream.adaptive/detail/Leia_backport/3/artifacts (cmake/addons/build/zips/inputstream.adaptive+windows-x86_64/inputstream.adaptive-2.4.3.zip)

**Comment by dagwieers** [comment]
I called out to all stakeholders for testing the upcoming v2.4.3 on Leia at https://github.com/peak3d/inputstream.adaptive/issues/387

**Comment by dagwieers** [comment]
@michaelarnauts It may be useful to open the Wiki for specific users (e.g. @peno64) or open it up to the public (it is a Git repository after all, so data loss is not an issue).

**Comment by michaelarnauts** [comment]
@dagwieers I've opened up this wiki. The inputstream page is quite outdated anyway, since the existing links don't seem to work anymore.

**Comment by dagwieers** [comment]
@michaelarnauts Maybe you ought to move working copies from Jenkins into the releases/downloads section of your latest release? I don't mind doing that if you give me those privileges.

**Comment by michaelarnauts** [comment]
Inputstream Adaptive 2.4.3 is released for Leia!

https://github.com/peak3d/inputstream.adaptive/releases/tag/2.4.3-Leia

This means that in the course of the next days, you will get an updated Inputstream Adaptive!

Platform overview:
* Windows: is already be updated.
* Ubuntu: the official Kodi PPA contains the update
* OSMC: awaiting for a Kodi 18.6 release. Should happen soon.
" Openelec: unknown

**Comment by dagwieers** [comment]
OSX also has an official update.

**Comment by dagwieers** [comment]
All platforms (except OSMC) currently have an updated **inputstream.adaptive** v2.4.3 so I think we can close this issue now.

**Comment by michaelarnauts** [comment]
I want to add a dependency on Inputstream Adaptive 2.4.3 in the addon.xml to enforce users to have at least this version.

**Comment by michaelarnauts** [comment]
I've added the dependency, and I'm waiting until the release is accepted in the Kodi repository before tagging 1.0.

**Comment by Essam311** [comment]
@peno64 Could you please explain the equivalent of the same steps here for compiling inputstream adaptive for windows on windows 10? Which software I will need for compiling inputstream adaptive on windows 10?

https://github.com/michaelarnauts/plugin.video.vtm.go/issues/101#issuecomment-541317533

**Comment by peno64** [comment]
@Essam311 I have no idea how it's done on Windows. For sure completely different. Jenkins is your best option here. But are you sure that you need another compilation for kodi 18.6?

**Comment by Essam311** [comment]
@peno64 OK, thank you, yes I need to compile this branch which has fix for a problem with the subtitle in my language with Kodi.

https://github.com/Essam311/inputstream.adaptive/tree/diacritical-marks

**Comment by Essam311** [comment]
@peno64 Is it possible to modify my fork from inpustream adaptive so Jenkins compile the files when I make a PR?

**Comment by peno64** [comment]
@Essam311 But is this change also in the Lea branch of inputstream.adaptive or only in master? If only in master then it will not work. Master is for the new kodi 19 (Matrix)

**Comment by peno64** [comment]
@Essam311 So what I actually mean is is the diacritical-marks branch a branch originally from master or from Leia_backport?
If it is not from Leia_backport then this will not be a good for kodi 18

**Comment by peno64** [comment]
@Essam311 Probably the Leia branch is also a good starting point as I see now it was also updated

**Comment by peno64** [comment]
@Essam311 I found this: https://github.com/peak3d/inputstream.adaptive/issues/18 and there it says at the end: "build instructions are inside kodi/docs/README.xxx files"

**Comment by Essam311** [comment]
@peno64 Thank you.
