### ISSUE TITLE
Video stops for a few seconds after an short advertisement

### ISSUE THREAD

**Issue by michaelarnauts** [michaelarnauts/plugin.video.vtm.go#139]
**Describe the bug**
Sometimes, the video stops for a few seconds after a short advertisment (mostly noticable after the VTM GO channel logo at the beginning of a program). The audio will continue giving a temporary a/v out of sync. It usually recovers fine after a few seconds.

This seems to be an issue in Kodi that has been tried to solve, but was reverted. I'm linking to relevant issues here to keep track of the progress.

* Issue at inputstream.adaptive: https://github.com/peak3d/inputstream.adaptive/issues/332
* Kodi merge request with a proposed fix: https://github.com/xbmc/xbmc/pull/16658
* Kodi revert of this fix: https://github.com/xbmc/xbmc/pull/16706

**Comment by michaelarnauts** [comment]
I think @dagwieers also reported this. Sometimes the video doesn't properly recover after an advertisement break. The player timeline looks like it restarted from the beginning, but there is no audio nor video.

The log only contains things like:
```
2020-03-08 19:07:15.078 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486502.229950
2020-03-08 19:07:15.124 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486455.781783
2020-03-08 19:07:15.171 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486409.270658
2020-03-08 19:07:15.217 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486362.848075
2020-03-08 19:07:15.264 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486316.366325
2020-03-08 19:07:15.308 T:2822222560   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2020-03-08 19:07:15.310 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486269.872074
2020-03-08 19:07:15.357 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486223.437158
2020-03-08 19:07:15.403 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486176.933907
2020-03-08 19:07:15.450 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486130.579075
2020-03-08 19:07:15.496 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486084.136866
2020-03-08 19:07:15.543 T:4025479904 WARNING: ActiveAE - large audio sync error: 1486038.175990
2020-03-08 19:07:15.589 T:4025479904 WARNING: ActiveAE - large audio sync error: 1485991.767114
2020-03-08 19:07:15.635 T:4025479904 WARNING: ActiveAE - large audio sync error: 1485944.701991

```

**Comment by KaleidoCR** [comment]
Hello, I am experiencing this same problem since Monday. 
No 'crash', screen just 'hangs' after the first commercial. Audio continues couple of seconds after freezing of image and status bar indicates playback...
Running Kodi 18.6 on latest Retropie 4.6 build on a raspberry pi 4B. Vtmgo version 10.0.2 and Inputstream Adaptive 2.4.4

**Comment by dagwieers** [comment]
@KaleidoCR Pausing briefly helps overcome this problem. It is annoying, but workable until we get this fixed.

**Comment by mediaminister** [comment]
This is fixed, merged and will be available for testing in the next nightly builds.

**Comment by michaelarnauts** [comment]
This has definitely improved since the fix, but I still see the video hang for a few seconds, and then fast forwards to catch up with the audio.

**Comment by keiem** [comment]
I posted issue #238 
Thus issue seems to expand and some streams become unwatchable.  The kids only look to Sara so i talk only about these streams but I guess it's also in other series.   When watching there is a lot of stuttering.  it's like you see when the mpeg dash ends a segment and starts with a new segment.  Yesterday we had also a few times the screen got black and kodi restarts.  Also the black parts in the beginning of the screen and before and in the commercials are still there.  We don't have the audio issue where the video stream has to catch up with the video stream.  Audio and video are always in sync.

**Comment by michaelarnauts** [comment]
Hmm, I have noticed the occasional issue, but not so much that it becomes onwatchable. Is the hardware powerfull enough for 1080p, or have you maybe disabled HW acceleration? You might find more clues in the Kodi log, however, errors with the playback is almost always related to Inputstream Adaptive, and is definitely not an easy fix...

**Comment by michaelarnauts** [comment]
If the stream is black during advertisements, are you maybe running an ad-blocker on a network level (Pi-Hole), or with a specific DNS server?

**Comment by keiem** [comment]
It's a Khadas VIM1, no ad-blocker, no special DNS, directly connected to the router.  Strange thing is, when we started watching VTM-Go, we didn't have problems at all, it started some time back, lets say a week before I posted issue #238 and it got worse over time.  Now the kids don't watch anymore on KODI as it's so worse, they take the tablet.

**Comment by michaelarnauts** [comment]
@keiem can you indicate what episode they tried to play, and when in the stream the issue occured? Also, it can help to provide a kodi log. You want to enable the kodi debug logging also (https://kodi.wiki/view/Log_file/Easy) and the `libcurl` and `video` component logging.

**Comment by michaelarnauts** [comment]
I just tried to play Sara Episode 175 (the last one) and it played trough without any issues.

**Comment by herrJones** [comment]
Hi,
When watching 'live', the stream stops a few times in every advertisement block.
It is OK once the program resumes.

We're using the standard play-store Kodi version on an NVidia Shield TV

**Comment by piejanssens** [comment]
Not sure if this is still expected, but I do have this issue on the latest stable Kodi Matrix playing `Sergio over de grens S01E01`.
